ENABLE_LINTERS:
- PYTHON_BLACK
- PYTHON_ISORT
- R_LINTR
- MARKDOWN_MARKDOWNLINT
- MARKDOWN_MARKDOWN_LINK_CHECK

TEXT_REPORTER: false
UPDATED_SOURCES_REPORTER: false
EMAIL_REPORTER: false
TAP files: false

MARKDOWN_DEFAULT_STYLE: "markdownlint"
SHOW_ELAPSED_TIME: true
APPLY_FIXES: "none"